"""
query_pipeline.py

End-to-end Wellness RAG pipeline:

    User question
        |
        v
    Deterministic safety layer
        |
        +-- crisis / ED-numeric --> safe response, STOP
        |
        v
    ChromaDB retrieval
        |
        v
    Source-diversity selection
        |
        v
    Grounded prompt
        |
        v
    Granite via Ollama
        |
        v
    Answer + sources

The retrieval stage uses the source-diversity strategy tested in
evaluate_retrieval.py. It fetches a wider candidate pool and prefers
different source documents so that a large source cannot dominate
the final context simply because it has more chunks.
"""

import argparse
import os
import sys
import re
import time
import numpy as np

import requests
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

from rag_config import CHROMA_DIR, COLLECTION_NAME, EMBEDDING_MODEL
from safety_layer import route_query



# ============================================================
# MEDICATION REQUEST CHECK
# ============================================================

MEDICATION_PATTERNS = [
    r"\bwhat medication\b",
    r"\bwhat medicine\b",
    r"\bwhich medication\b",
    r"\bwhich medicine\b",
    r"\bwhat drug\b",
    r"\bwhich drug\b",
    r"\bwhat should i take\b",
    r"\bwhat can i take\b",
    r"\bmedicine for\b",
    r"\bmedication for\b",
    r"\bdrug for\b",
]

_MEDICATION_REGEX = re.compile(
    "|".join(MEDICATION_PATTERNS),
    re.IGNORECASE
)

MEDICATION_RESPONSE = (
    "I can't recommend or select a specific medication for anxiety. "
    "A qualified healthcare professional can assess your situation and "
    "discuss appropriate treatment options, including potential benefits "
    "and side effects. If your symptoms are severe, worsening, or "
    "interfering with daily life, consider seeking professional support."
)


def check_medication_request(user_input: str) -> bool:
    return bool(_MEDICATION_REGEX.search(user_input))



# ============================================================
# CONFIG
# ============================================================

TOP_K = 3
CANDIDATE_K = 10
MAX_PER_SOURCE = 1
EVIDENCE_DISTANCE_THRESHOLD = 1.25

OLLAMA_URL = os.getenv(
    "WELLNESS_OLLAMA_URL",
    "http://localhost:11434/api/generate",
)

# IMPORTANT:
# Change this if `ollama list` shows a different Granite model tag.
GRANITE_MODEL = "granite4.1:3b"

TEMPERATURE = 0.3
_embeddings = None


# ============================================================
# PROMPT
# ============================================================

SYSTEM_PROMPT_TEMPLATE = """Role: You are a supportive wellness information assistant.

Task: Answer the user's current question using the verified evidence
and conversation context provided below.

The Verified evidence section contains the only factual Wellness
information that may be used in the answer.

Conversation context is important for understanding what the user
means when they use words such as "it", "this", "that", "they", "them",
"more", or other short follow-up questions.

Use earlier conversation to resolve references and understand the
user's situation. Do not treat the current question as an isolated
question when the conversation provides relevant context.

Reference resolution rules:
- For vague follow-up words such as "this", "that", "it", "these",
  "those", "more", or "what about it", use the Most recent User
  message as the primary reference.
- The Most recent User message is the default subject when the
  current question does not explicitly name a topic.
- Answer the current question primarily about that subject.
- Do not switch to an older topic merely because the older topic
  is more prominent in the conversation.
- Older conversation may provide supporting context, but it must
  not replace the primary subject identified by the Most recent
  User message.
- If the user asks "What should I do about this?" immediately after
  discussing a topic, interpret "this" as that immediately preceding
  topic.

The conversation context contains previous User and Assistant
messages.

Previous User messages describe what the user actually said.
Previous Assistant messages are prior responses generated by the
assistant and must not be treated as facts about the user's life,
symptoms, history, preferences, or circumstances unless the user
explicitly confirmed those details.

Use previous User messages to understand the user's situation,
preferences, and intent.

Use the Wellness knowledge for factual wellness information.
Previous Assistant messages may help preserve conversational
continuity, but they are not an independent source of truth.

Do not introduce facts, treatments, numbers, or recommendations that
are not supported by the Wellness knowledge.

Verified evidence:
{verified_evidence}

Context:
{context}

Evidence-first answering:
- Before writing the answer, identify the specific information in
  Context that directly supports the answer.

- Answer only using information that can be directly supported by
  the retrieved Context.

- Do not infer, elaborate, generalize, or complete missing information
  using pretrained knowledge.

- If a detail is not explicitly present in Context, leave it out.

- If Context supports only part of the answer, answer only that part.

- For definitions, use only the definition and details explicitly
  present in Context. Do not add typical symptoms, examples,
  durations, diagnostic criteria, causes, or other details unless
  Context contains them.

- For questions asking for types, causes, symptoms, treatments,
  techniques, or recommendations, include only the items explicitly
  supported by Context.

- Prefer a shorter evidence-supported answer over a more complete
  answer containing unsupported information.

- Do not mention this evidence-checking process in the final answer.

Format:
Answer directly and concisely.
For simple questions, use 2–4 sentences.
Use a short numbered or bulleted list only when needed.
Do not repeat information.
Do not add unnecessary background information or closing remarks.
Use clear, supportive language.
No unnecessary medical jargon.

Exclusions:
- Never diagnose, prescribe, recommend, select, or compare
  specific medications or dosages. If medication is relevant, state only
  that a qualified healthcare professional can discuss treatment options.

- Never diagnose or label the user's personal symptoms with a named
  mental-health disorder.

- When a user describes personal symptoms and asks what they were,
  do not identify the symptoms as a specific disorder or state that
  the user had, has, may have, might have, or may be experiencing
  that disorder.

- If the retrieved Wellness knowledge describes those symptoms in
  relation to a disorder, explain the general educational connection
  without applying the disorder label to the user's individual
  experience.

- Prefer wording such as "Those symptoms can occur during panic
  attacks" rather than "That sounds like a panic attack."

- If the available context is insufficient to determine what caused
  the user's symptoms, say that the symptoms can have different
  causes and that the available information cannot determine the cause.

- Keep every factual claim grounded in the Wellness knowledge provided
  in Context.

- Treat the retrieved Context as the only source of factual Wellness
  information. Do not use pretrained knowledge to add details that are
  absent from the Context.

- Use only symptoms, causes, treatments, coping strategies, definitions,
  numbers, timeframes, or other factual details that are explicitly
  supported by the Context.

- Do not expand a retrieved definition with additional symptoms,
  diagnostic criteria, causes, treatments, examples, or clinical details
  from general knowledge.

- Do not add specific techniques, methods, routines, or recommendations
  unless the Context explicitly supports them.

- When the Context supports only part of an answer, answer only that
  supported part. Do not fill the missing part from general knowledge.

- If the Context does not contain enough information to answer the
  question, say so honestly instead of completing the answer from
  pretrained knowledge.

- Treat previous Assistant messages as conversational context only.
  They are not evidence for factual Wellness claims.

- Do not claim that the user previously said, experienced, preferred,
  or did something unless that information appears in a previous User
  message.

- Avoid broad normalizing or reassuring statements about the user's
  personal symptoms, such as "this is completely normal" or "this is
  common," unless the provided Context directly supports that framing.

- Never invent facts that are not present in the Context.

{history_block}
Use the conversation context to understand the user's intent and
resolve references in the current question.

Question:
{question}
"""


# ============================================================
# LOAD VECTOR DATABASE
# ============================================================

def get_vector_db():
    global _embeddings

    if _embeddings is None:
        embedding_start = time.perf_counter()

        _embeddings = HuggingFaceEmbeddings(
    model_name=EMBEDDING_MODEL,
    model_kwargs={
        "local_files_only": True
    },
    show_progress=False
)

        embedding_time = time.perf_counter() - embedding_start

        print(
            f"[PERFORMANCE] Embedding model initialization: "
            f"{embedding_time:.3f}s"
        )

    chroma_start = time.perf_counter()

    vector_db = Chroma(
        collection_name=COLLECTION_NAME,
        embedding_function=_embeddings,
        persist_directory=str(CHROMA_DIR),
    )

    chroma_time = time.perf_counter() - chroma_start

    print(
        f"[PERFORMANCE] Chroma initialization: "
        f"{chroma_time:.3f}s"
    )

    return vector_db

# ============================================================
# SOURCE-DIVERSITY RETRIEVAL
# ============================================================

def retrieve_context(
    vector_db,
    question: str,
    k: int = TOP_K,
    candidate_k: int = CANDIDATE_K,
    max_per_source: int = MAX_PER_SOURCE,
):
    """
    Retrieve a wider candidate pool, then select up to k chunks while
    limiting the number of chunks from the same source.

    The original source-diversity selection strategy is preserved.
    Retrieval distances are retained so Phase 6 can assess whether
    sufficient evidence exists before generation.
    """

    candidates = vector_db.similarity_search_with_score(
        question,
        k=candidate_k,
    )

    candidate_docs = [
        (doc, float(score))
        for doc, score in candidates
    ]

    selected = []
    source_counts = {}

    # First pass:
    # Prefer one chunk from each source.
    for doc, score in candidate_docs:

        source_id = str(
            doc.metadata.get("source_id", "?")
        )

        count = source_counts.get(
            source_id,
            0,
        )

        if count >= max_per_source:
            continue

        selected.append(
            (doc, score)
        )

        source_counts[source_id] = count + 1

        if len(selected) >= k:
            break

    # Fallback:
    # If there aren't enough distinct sources, fill remaining slots
    # using the original similarity ranking.
    if len(selected) < k:

        selected_ids = {
            id(doc)
            for doc, _ in selected
        }

        for doc, score in candidate_docs:

            if id(doc) in selected_ids:
                continue

            selected.append(
                (doc, score)
            )

            if len(selected) >= k:
                break

    context = [
        {
            "text": doc.page_content,
            "source_id": str(
                doc.metadata.get(
                    "source_id",
                    "?",
                )
            ),
            "title": doc.metadata.get(
                "title",
                "Unknown source",
            ),
            "organization": doc.metadata.get(
                "organization",
                "Unknown",
            ),
             "retrieval_distance": score,
        }
        for doc, score in selected
    ]

    best_distance = candidate_docs[0][1]

    return context, best_distance

# ============================================================
# CONVERSATION CONTEXT
# ============================================================

RECENT_MESSAGES = 6
MAX_RELEVANT_OLDER_UNITS = 5
RELEVANCE_THRESHOLD = 0.30


def cosine_similarity(a, b):
    """
    Calculate cosine similarity between two embedding vectors.
    """

    a = np.asarray(a)
    b = np.asarray(b)

    denominator = np.linalg.norm(a) * np.linalg.norm(b)

    if denominator == 0:
        return 0.0

    return float(np.dot(a, b) / denominator)


def build_conversation_units(history: list) -> list:
    """
    Group conversation turns into user/assistant units.

    Each user message is paired with the assistant response
    immediately following it, when available.

    This preserves the meaning of a conversation exchange
    instead of evaluating individual messages in isolation.
    """

    units = []

    index = 0

    while index < len(history):

        message = history[index]

        if message.get("role") != "user":
            index += 1
            continue

        user_content = str(
            message.get("content", "")
        ).strip()

        if not user_content:
            index += 1
            continue

        unit_messages = [message]

        # Pair the user's message with the following
        # assistant response when one exists.
        if (
            index + 1 < len(history)
            and history[index + 1].get("role") == "assistant"
        ):
            unit_messages.append(history[index + 1])

            index += 2

        else:
            index += 1

        units.append(
            {
                "messages": unit_messages,
                "start_index": index - len(unit_messages),
            }
        )

    return units


def format_conversation_unit(unit: dict) -> str:
    """
    Convert a conversation unit into text suitable for embedding.
    """

    lines = []

    for message in unit["messages"]:

        role = message.get("role")

        speaker = (
            "User"
            if role == "user"
            else "Assistant"
        )

        content = str(
            message.get("content", "")
        ).strip()

        if content:
            lines.append(
                f"{speaker}: {content}"
            )

    return "\n".join(lines)


def select_conversation_context(
    question: str,
    history: list | None = None,
) -> list:
    """
    Select conversation context.

    For vague follow-up questions such as "this", "that", "it",
    or "more", the immediately preceding User message is treated
    as the primary reference.

    For normal questions, recent conversation plus semantically
    relevant older conversation is retained.
    """

    if not history:
        return []

    # --------------------------------------------------------
    # Detect vague follow-up question
    # --------------------------------------------------------

    vague_patterns = [
        r"\bwhat should i do about this\b",
        r"\bwhat should i do about that\b",
        r"\bwhat can i do about this\b",
        r"\bwhat can i do about that\b",
        r"\bwhat about this\b",
        r"\bwhat about that\b",
        r"\bwhat about it\b",
        r"\bhow do i handle this\b",
        r"\bhow do i handle that\b",
        r"\bcan you give me more\b",
        r"\bgive me more\b",
    ]

    is_vague_reference = any(
        re.search(
            pattern,
            question.strip().lower(),
        )
        for pattern in vague_patterns
    )

    # --------------------------------------------------------
    # Deterministic handling for vague references
    # --------------------------------------------------------

    if is_vague_reference:

        # Find the most recent User message before the current
        # question.
        previous_user_messages = [
            message
            for message in history
            if message.get("role") == "user"
        ]

        if not previous_user_messages:
            return history[-RECENT_MESSAGES:]

        latest_user_message = previous_user_messages[-1]

        latest_user_index = history.index(
            latest_user_message
        )

        # Include the previous exchange plus a small amount
        # of recent context for conversational continuity.
        start_index = max(
            0,
            latest_user_index - 1,
        )

        return history[start_index:]

    # --------------------------------------------------------
    # Normal conversation handling
    # --------------------------------------------------------

    if len(history) <= RECENT_MESSAGES:
        return history

    recent = history[-RECENT_MESSAGES:]
    older = history[:-RECENT_MESSAGES]

    # --------------------------------------------------------
    # Build conversation units from older history.
    # --------------------------------------------------------

    units = build_conversation_units(older)

    if not units:
        return recent

    # --------------------------------------------------------
    # Create embeddings using the same model as the RAG system.
    # --------------------------------------------------------

    embeddings = _embeddings

    question_embedding = embeddings.embed_query(
        question
    )

    scored_units = []

    for unit in units:

        # Use only the user's message for semantic relevance.
        user_message = unit["messages"][0]

        unit_text = str(
            user_message.get("content", "")
        ).strip()

        if not unit_text:
            continue

        unit_embedding = embeddings.embed_query(
            unit_text
        )

        semantic_score = cosine_similarity(
            question_embedding,
            unit_embedding,
        )

        if len(units) > 1:
            recency_score = (
                unit["start_index"] / (len(older) - 1)
            )
        else:
            recency_score = 1.0

        combined_score = (
            semantic_score * 0.70
            + recency_score * 0.30
        )

        scored_units.append(
            {
                "unit": unit,
                "score": combined_score,
                "semantic_score": semantic_score,
            }
        )

    # --------------------------------------------------------
    # Rank older conversation units.
    # --------------------------------------------------------

    scored_units.sort(
        key=lambda item: item["score"],
        reverse=True,
    )

    relevant_units = [
        item
        for item in scored_units[
            :MAX_RELEVANT_OLDER_UNITS
        ]
        if item["semantic_score"] >= RELEVANCE_THRESHOLD
    ]

    # --------------------------------------------------------
    # Restore chronological order.
    # --------------------------------------------------------

    relevant_units.sort(
        key=lambda item: item["unit"]["start_index"]
    )

    # --------------------------------------------------------
    # Flatten selected units.
    # --------------------------------------------------------

    older_messages = []

    for item in relevant_units:
        older_messages.extend(
            item["unit"]["messages"]
        )

    # --------------------------------------------------------
    # Return older relevant context followed by recent context.
    # --------------------------------------------------------

    return older_messages + recent

# ============================================================
# PROMPT CONSTRUCTION
# ============================================================

def build_prompt(
    question: str,
    chunks: list,
    history: list | None = None,
) -> str:

    conversation_context = select_conversation_context(
        question,
        history,
    )

    context_block = "\n\n".join(
        f"[{chunk['organization']} - {chunk['title']}]\n"
        f"{chunk['text']}"
        for chunk in chunks
    )

    verified_evidence = extract_supported_evidence(
        question,
        chunks,
    )
    
    if conversation_context:
        lines = ["Conversation context:"]

        for turn in conversation_context:
            speaker = (
                "User"
                if turn["role"] == "user"
                else "Assistant"
            )

            lines.append(
                f"{speaker}: {turn['content']}"
            )

        history_block = "\n".join(lines) + "\n\n"

        # Explicitly identify the most recent User message.
        # This helps resolve vague references such as "this", "that",
        # "it", and "more".
        recent_user_messages = [
            turn["content"]
            for turn in conversation_context
            if turn["role"] == "user"
        ]

        if recent_user_messages:
         history_block += (
        "Most recent User message:\n"
        f"{recent_user_messages[-1]}\n\n"
        "Reference resolution:\n"
        "If the current question uses a vague reference such as "
        "\"this\", \"that\", \"it\", \"these\", \"those\", or \"more\", "
        "treat the Most recent User message as the primary subject "
        "of that reference.\n"
        "Do not switch to an older topic unless the current question "
        "explicitly names that older topic.\n\n"
    )

    else:
        history_block = ""

    print("\n" + "=" * 60)
    print("DEBUG — SELECTED CONVERSATION CONTEXT")
    print("=" * 60)
    print(history_block)
    print("=" * 60 + "\n")

    return SYSTEM_PROMPT_TEMPLATE.format(
        context=context_block,
        history_block=history_block,
        verified_evidence=verified_evidence,
        question=question,
    )

# ============================================================
# GRANITE / OLLAMA
# ============================================================

# ============================================================
# PHASE 6 — EVIDENCE EXTRACTION
# ============================================================

EVIDENCE_EXTRACTION_PROMPT = """You are an evidence extraction assistant.

Your task is to extract only factual information that is explicitly
stated in the provided Wellness knowledge.

Rules:
- Use ONLY the provided Wellness knowledge.
- Copy or closely preserve the meaning of information explicitly stated
  in the knowledge.
- Do not use pretrained knowledge.
- Do not infer missing information.
- Do not add examples, symptoms, causes, treatments, definitions,
  durations, numbers, or recommendations that are not explicitly stated.
- If the knowledge does not contain information relevant to the
  question, output exactly:
  NO_SUPPORTED_EVIDENCE
- Keep the extracted evidence short and factual.
- Do not answer the user's question.
- Do not provide explanations beyond the extracted evidence.

Wellness knowledge:
{context}

Question:
{question}

Supported evidence:
"""


def extract_supported_evidence(
    question: str,
    chunks: list,
) -> str:

    context_block = "\n\n".join(
        f"[{chunk['organization']} - {chunk['title']}]\n"
        f"{chunk['text']}"
        for chunk in chunks
    )

    prompt = EVIDENCE_EXTRACTION_PROMPT.format(
        context=context_block,
        question=question,
    )

    return call_granite(prompt).strip()

def call_granite(prompt: str) -> str:

    try:
        response = requests.post(
            OLLAMA_URL,
            json={
                "model": GRANITE_MODEL,
                "prompt": prompt,
                "stream": False,
                "keep_alive": "10m",
                "options": {
                    "temperature": TEMPERATURE,
                    "num_predict": 256,
                },
            },
            timeout=120,
        )

        response.raise_for_status()

    except requests.exceptions.ConnectionError as error:
     raise RuntimeError(
        "Couldn't reach Ollama at http://localhost:11434. "
        "Make sure Ollama is running."
    ) from error

    except requests.exceptions.RequestException as error:
     raise RuntimeError(
        f"Ollama request failed: {error}"
    ) from error

    try:
        data = response.json()
        
    except ValueError:
        return "[ERROR] Ollama returned invalid JSON."

    print(
    f"[PERFORMANCE] Ollama load duration: "
    f"{data.get('load_duration', 0) / 1_000_000_000:.3f}s"
)

    print(
    f"[PERFORMANCE] Ollama prompt eval: "
    f"{data.get('prompt_eval_duration', 0) / 1_000_000_000:.3f}s"
)

    print(
    f"[PERFORMANCE] Ollama generation: "
    f"{data.get('eval_duration', 0) / 1_000_000_000:.3f}s"
)

    print(
    f"[PERFORMANCE] Ollama generated tokens: "
    f"{data.get('eval_count', 0)}"
)
    
    answer = data.get(
    "response",
    "[ERROR] No response returned by Granite.",
)

    print(f"[PERFORMANCE] Granite output characters: {len(answer)}")

    return answer


# ============================================================
# END-TO-END ANSWER
# ============================================================

def answer_query(
    vector_db,
    question: str,
    history: list | None = None,
) -> dict:

    total_start = time.perf_counter()

    # --------------------------------------------------------
    # STEP 1 — SAFETY
    # --------------------------------------------------------

    safety_start = time.perf_counter()

    safety_result = route_query(question)

    safety_time = time.perf_counter() - safety_start

    if safety_result["route"] != "normal":

        print("\n" + "=" * 60)
        print("PERFORMANCE")
        print("=" * 60)
        print(f"Safety: {safety_time:.3f}s")
        print(f"Total:  {time.perf_counter() - total_start:.3f}s")
        print("=" * 60 + "\n")

        # IMPORTANT:
        # Retrieval and Granite are completely bypassed.
        return {
            "route": safety_result["route"],
            "answer": safety_result["response"],
            "sources": [],
            "context_chunks": [],
        }

    # --------------------------------------------------------
    # STEP 2 — RETRIEVAL
    # --------------------------------------------------------

    retrieval_start = time.perf_counter()

    retrieval_result = retrieve_context(
      vector_db,
      question,
      k=TOP_K,
      candidate_k=CANDIDATE_K,
      max_per_source=MAX_PER_SOURCE,
    )

    if isinstance(retrieval_result, tuple):
       chunks, best_distance = retrieval_result
    else:
      # Backward-compatible path for existing tests/mocks
      # that return the original context-list format.
      chunks = retrieval_result
      best_distance = None

    retrieval_time = time.perf_counter() - retrieval_start

    if not chunks:

        print("\n" + "=" * 60)
        print("PERFORMANCE")
        print("=" * 60)
        print(f"Safety:     {safety_time:.3f}s")
        print(f"Retrieval:  {retrieval_time:.3f}s")
        print(f"Total:      {time.perf_counter() - total_start:.3f}s")
        print("=" * 60 + "\n")

        return {
            "route": "normal",
            "answer": (
                "I don't have enough information in my current "
                "knowledge base to answer that."
            ),
            "sources": [],
            "context_chunks": [],
        }

    # --------------------------------------------------------
    # STEP 2B — PHASE 6 EVIDENCE SUFFICIENCY GATE
    # --------------------------------------------------------
    
    if (
        best_distance is not None
        and best_distance > EVIDENCE_DISTANCE_THRESHOLD
    ):
        return {
            "route": "normal",
            "answer": (
                "I don't have enough information in my current "
                "knowledge base to answer that reliably."
            ),
            "sources": [],
            "context_chunks": [],
        }
    
    # --------------------------------------------------------
    # STEP 3 — PROMPT
    # --------------------------------------------------------

    prompt_start = time.perf_counter()

    prompt = build_prompt(
        question,
        chunks,
        history,
    )
    print(
    f"[PERFORMANCE] Granite prompt characters: "
    f"{len(prompt)}"
    )

    prompt_time = time.perf_counter() - prompt_start

    # --------------------------------------------------------
    # STEP 4 — GRANITE
    # --------------------------------------------------------

    ollama_start = time.perf_counter()

    answer = call_granite(prompt)

    ollama_time = time.perf_counter() - ollama_start

    # --------------------------------------------------------
    # STEP 5 — SOURCE LIST
    # --------------------------------------------------------

    sources = []
    seen = set()

    for chunk in chunks:

        key = (
            chunk["organization"],
            chunk["title"],
        )

        if key in seen:
            continue

        seen.add(key)

        sources.append(
            {
                "organization": chunk["organization"],
                "title": chunk["title"],
            }
        )

    # --------------------------------------------------------
    # PERFORMANCE REPORT
    # --------------------------------------------------------

    total_time = time.perf_counter() - total_start

    print("\n" + "=" * 60)
    print("PERFORMANCE")
    print("=" * 60)
    print(f"Safety:          {safety_time:.3f}s")
    print(f"Retrieval:       {retrieval_time:.3f}s")
    print(f"Prompt:          {prompt_time:.3f}s")
    print(f"Ollama/Granite:  {ollama_time:.3f}s")
    print("-" * 60)
    print(f"TOTAL:           {total_time:.3f}s")
    print("=" * 60 + "\n")

    return {
        "route": "normal",
        "answer": answer,
        "sources": sources,
        "context_chunks": chunks,
    }


# ============================================================
# OUTPUT
# ============================================================

def print_result(result: dict):

    print("\n" + "=" * 60)
    print(f"ROUTE: {result['route']}")
    print("=" * 60)

    print("\nANSWER:")
    print(result["answer"])

    if result["sources"]:

        print("\nSOURCES:")

        for source in result["sources"]:
            print(
                f"  - {source['organization']}: "
                f"{source['title']}"
            )

    print()


# ============================================================
# CLI
# ============================================================

def main():

    parser = argparse.ArgumentParser(
        description="Wellness RAG query pipeline"
    )

    parser.add_argument(
        "--once",
        type=str,
        default=None,
        help="Answer one question and exit",
    )

    args = parser.parse_args()

    print("Loading Wellness RAG...")
    print(f"Embedding model: {EMBEDDING_MODEL}")
    print(f"Candidate pool: {CANDIDATE_K}")
    print(f"Final context chunks: {TOP_K}")
    print(f"Max chunks per source: {MAX_PER_SOURCE}")
    print(f"Granite model: {GRANITE_MODEL}")

    vector_db = get_vector_db()

    print("\nPipeline ready.\n")

    # --------------------------------------------------------
    # ONE QUESTION
    # --------------------------------------------------------

    if args.once:

        result = answer_query(
            vector_db,
            args.once,
        )

        print_result(result)
        return

    # --------------------------------------------------------
    # INTERACTIVE MODE
    # --------------------------------------------------------

    print(
        "Wellness RAG Bot\n"
        "Type a question or 'quit' to exit.\n"
    )

    while True:

        try:
            question = input("You: ").strip()

        except (EOFError, KeyboardInterrupt):

            print("\nExiting.")
            break

        if not question:
            continue

        if question.lower() in {
            "quit",
            "exit",
        }:
            break

        result = answer_query(
            vector_db,
            question,
        )

        print_result(result)


if __name__ == "__main__":
    sys.exit(main())